spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
# Invalida el data.sql
spring.sql.init.mode=never
app.security.secretkey=2604a78c0f4e263277565d52ddd684624ce50d775fc0fdd18b3b1c73e2b47032

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.docker.compose.enabled=false
app.security.secretkey=cualquier-valor-de-test-no-importa-cual
spring.jpa.show-sql=false