services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./ICESI-Gym-Backend
      dockerfile: Dockerfile
    container_name: spring_backend
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_SECURITY_SECRETKEY: 2604a78c0f4e263277565d52ddd684624ce50d775fc0fdd18b3b1c73e2b47032
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./ICESI-Gym-Frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: