$kind: http-request
url: "{{baseUrl}}/api/v1/roles"
method: GET
headers:
  Authorization: Bearer {{token}}
scripts:
  - type: afterResponse
    code: "pm.test(\"Status 200\", function () {\r

      \    pm.response.to.have.status(200);\r

      });\r

      pm.test(\"Response is array\", function () {\r

      \    pm.expect(pm.response.json()).to.be.an(\"array\");\r

      });\r

      pm.test(\"Array is not empty\", function () {\r

      \    pm.expect(pm.response.json().length).to.be.above(0);\r

      });"
    language: text/javascript
order: 4000
