spring.application.name=proyectoFinal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.srbntzbcetauduysxtiv}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dMPYRtZB4NVm3Zel}
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# server.port=8080
spring.docker.compose.enabled=false
spring.jpa.properties.hibernate.format_sql=true
app.security.secretkey=2604a78c0f4e263277565d52ddd684624ce50d775fc0fdd18b3b1c73e2b47032
app.security.expirationMinutes=60
server.forward-headers-strategy=native